"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { EnvironmentKey } from "@/lib/types";
import { useWorkspace } from "../workspace-provider";

export function ApiView(){const {activeEnvironment,activeEnvironmentId}=useWorkspace();const[keys,setKeys]=useState<EnvironmentKey[]>([]);const[newKey,setNewKey]=useState("");const[loading,setLoading]=useState(true);const[rotating,setRotating]=useState(false);const[error,setError]=useState("");async function load(){if(!activeEnvironmentId){setKeys([]);setLoading(false);return;}setLoading(true);try{setKeys(await api.get<EnvironmentKey[]>(`/environments/${activeEnvironmentId}/keys`));}catch(e){setError(e instanceof Error?e.message:"Unable to load SDK keys");}finally{setLoading(false);}}useEffect(()=>{void load();},[activeEnvironmentId]);async function rotate(){if(!activeEnvironmentId)return;setRotating(true);setError("");setNewKey("");try{const result=await api.post<EnvironmentKey>(`/environments/${activeEnvironmentId}/keys/rotate`);setNewKey(result.sdk_key||"");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to rotate SDK key");}finally{setRotating(false);}}const origin=typeof window!=="undefined"?window.location.origin:"http://localhost:3000";const code=`curl -X POST "${process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000/api/v1"}/evaluate/${activeEnvironment?.key||"production"}/checkout-redesign" \\
  -H "Content-Type: application/json" \\
  -H "X-Feature-Key: ${newKey||"ffp_xxxxxxxxxxxxxxxxxxxxxxxxx"}" \\
  -d '{"user_id":"user-123","attributes":{"plan":"pro"}}'`;return <div className="page-content"><div className="page-head"><div><p className="eyebrow">Developer access</p><h1>API & SDK</h1><p>Environment-scoped credentials and the public evaluation contract for application integration.</p></div><button className="button button-dark" disabled={!activeEnvironmentId||rotating} onClick={()=>void rotate()}>{rotating?"Rotating…":"Rotate SDK key"}</button></div>{error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{newKey&&<div className="key-reveal"><strong>New SDK key — copy it now</strong><div><code>{newKey}</code></div></div>}<div className="two-col"><div className="panel"><div className="panel-head"><strong>Evaluation example</strong><span className="badge live">server-backed</span></div><div className="panel-body"><pre className="code-block">{code}</pre><p className="muted">The evaluation endpoint is authenticated by the environment SDK key. Keys are stored as SHA-256 hashes and only the one-time secret is returned during creation/rotation.</p><p className="muted">Console origin: {origin}</p></div></div><div className="panel"><div className="panel-head"><strong>{activeEnvironment?.name||"Environment"} keys</strong><span className="muted">{keys.length} record{keys.length===1?"":"s"}</span></div><div className="panel-body">{loading?<div className="loading">Loading keys…</div>:keys.map(key=><div className="quick-action" key={key.id} style={{marginBottom:8}}><div><strong>{key.name}</strong><span>{key.key_prefix} · {key.revoked_at?"revoked":"active"}</span></div><span className={`badge ${key.revoked_at?"":"live"}`}>{key.revoked_at?"revoked":"active"}</span></div>)}{!keys.length&&!loading&&<div className="notice">Create an environment in Settings to issue its first SDK key.</div>}</div></div></div></div>}
