"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { api } from "@/lib/api";
import type { FeatureFlag, ProjectOverview } from "@/lib/types";
import { formatRelativeTime } from "@/lib/utils";
import { useWorkspace } from "../workspace-provider";

export function OverviewView() {
  const { activeProjectId, activeProject, activeEnvironmentId, environments } = useWorkspace();
  const [overview, setOverview] = useState<ProjectOverview | null>(null); const [flags, setFlags] = useState<FeatureFlag[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!activeProjectId) return; Promise.all([api.get<ProjectOverview>(`/projects/${activeProjectId}/overview`), api.get<FeatureFlag[]>(`/projects/${activeProjectId}/flags`)]).then(([o,f])=>{setOverview(o);setFlags(f)}).catch(err=>setError(err instanceof Error?err.message:"Unable to load project")); }, [activeProjectId]);
  if (!activeProject) return <div className="page-content"><div className="empty-state"><h3>Create your first project</h3><p>A workspace needs a project before feature flags can be created. Use the project settings route once it is available.</p><Link className="button button-dark" href="/app/flags">Go to flags</Link></div></div>;
  return <div className="page-content"><div className="page-head"><div><h1>{activeProject.name}</h1><p>{activeProject.description || "Control runtime delivery for this project."}</p></div><Link className="button button-dark" href="/app/flags">Manage flags <span>→</span></Link></div>{error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}<div className="card-grid"><div className="metric-card"><div className="metric-label">Active flags</div><div className="metric-value">{overview?.flags ?? "—"}</div></div><div className="metric-card"><div className="metric-label">Enabled now</div><div className="metric-value">{overview?.enabled_flags ?? "—"}</div></div><div className="metric-card"><div className="metric-label">Environments</div><div className="metric-value">{overview?.environments ?? environments.length}</div></div><div className="metric-card"><div className="metric-label">Targeting rules</div><div className="metric-value">{overview?.targeting_rules ?? "—"}</div></div></div><div className="two-col"><div className="panel"><div className="panel-head"><strong>Flag rollout snapshot</strong><Link href="/app/flags" className="text-button">View all</Link></div><div className="table-wrap"><table><thead><tr><th>Flag</th><th>Type</th><th>Environment</th><th>Status</th></tr></thead><tbody>{flags.slice(0,7).map(flag=>{const state=flag.environment_states.find(s=>s.environment_id===activeEnvironmentId);return <tr key={flag.id}><td><div className="flag-name"><strong>{flag.name}</strong><span className="flag-key">{flag.key}</span></div></td><td><span className="badge">{flag.flag_type}</span></td><td>{environments.find(e=>e.id===activeEnvironmentId)?.name || "—"}</td><td><span className={`badge ${state?.enabled ? "live" : ""}`}>{state?.enabled ? "enabled" : "off"}</span></td></tr>})}{!flags.length&&<tr><td colSpan={4}><div className="empty-state"><h3>No flags yet</h3><p>Create a typed flag to start controlling releases.</p></div></td></tr>}</tbody></table></div></div><div className="panel"><div className="panel-head"><strong>Recent changes</strong><Link href="/app/audit" className="text-button">Audit log</Link></div><div className="audit-list">{overview?.recent_audit.slice(0,7).map(item=><div key={item.id} className="audit-row"><span className="audit-time">{formatRelativeTime(item.created_at)}</span><span className="audit-action">{item.action}</span><span className="audit-detail">{JSON.stringify(item.details)}</span></div>)}{!overview?.recent_audit.length&&<div className="empty-state"><p>No changes recorded yet.</p></div>}</div></div></div></div>;
}
